version: '2'
services:
    jorgeluiskyrkos-app:
        image: jorgeluiskyrkos
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jorgeluiskyrkos-postgresql:5432/jorgeluiskyrkos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jorgeluiskyrkos-postgresql:
        extends:
            file: postgresql.yml
            service: jorgeluiskyrkos-postgresql
