version: '2'
services:
    jorgeluiskyrkos-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jorgeluiskyrkos/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jorgeluiskyrkos
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
